### ISSUE TITLE
[develop] No module named 'pyopenapi.spec.base'

### ISSUE THREAD

**Issue by wapiflapi** [pyopenapi/pyopenapi#9]
I'm very new to this project, I'm looking for a way to manipulate OpenAPI v3 spec files from python and looking at what's around before starting to code something from scratch. This project looks promising but when I wanted to try it out I ran in some issues. I have to say I'm testing using `develop`, it's perfectly OK if you know it's broken & I'm not supposed to use it ;) I'm just looking around and trying to get a feel for the project before maybe contributing.

It looks like commit a99dfb95fcd5b8e25b29bc4b0e2a1fc288957534 deleted  `pyopenapi.base`, claiming it wasn't useful anymore, except it still seems to be used:

```pytb
>>> from pyopenapi import App
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    from pyopenapi import App
  File ".../pyopenapi/pyopenapi/__init__.py", line 2, in <module>
    from .core import App, Security
  File ".../pyopenapi/pyopenapi/core.py", line 8, in <module>
    from .scan import Scanner
  File ".../pyopenapi/pyopenapi/scan.py", line 2, in <module>
    from .spec.base import BaseObj
ImportError: No module named 'pyopenapi.spec.base'
```

When checking out commit e4219acf6d5bce7a4eca4a2bd01a1462d2294be2 it seems to be working fine.

Is this something that should be fixed by using the new code in `base2` in places where the old code is still used? Is this something you'd like help with? Is it OK for someone new to the project to try and tackle this issue?

**Comment by mission-liao** [comment]
@wapiflapi This project is still under development, and I think it's not very easy for others to contribute something at this stage, since I'm current **refactor** this project into two parts:
 - a migration library that provides an **OpenAPI version backward compatible** layer to make it easier to develop tools for OpenAPI.
 - other stuffs

I would have some time to make this "refactor" reach some checkpoint recently. Before that happens, those branches are supposed to be broken, :(

**Comment by mission-liao** [comment]
@wapiflapi I just merge a `unittest pass` PR into `develop` branch, if you are willing to give a try, you can refer to `pyopenapi.migration.tests.utils.SampleApp` for an example about how to use this project
